# Generated by Django 4.2 on 2023-05-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EURUSD_D1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Дата фрейма')),
                ('open', models.FloatField(verbose_name='Цена открытия')),
                ('high', models.FloatField(verbose_name='Максимум торгового диапазона')),
                ('low', models.FloatField(verbose_name='Минимум торгового диапазона')),
                ('close', models.FloatField(verbose_name='Цена закрытия')),
                ('tick_volume', models.IntegerField()),
                ('spred', models.IntegerField(null=True, verbose_name='Спред')),
                ('real_volume', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EURUSD_H1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Дата фрейма')),
                ('open', models.FloatField(verbose_name='Цена открытия')),
                ('high', models.FloatField(verbose_name='Максимум торгового диапазона')),
                ('low', models.FloatField(verbose_name='Минимум торгового диапазона')),
                ('close', models.FloatField(verbose_name='Цена закрытия')),
                ('tick_volume', models.IntegerField()),
                ('spred', models.IntegerField(null=True, verbose_name='Спред')),
                ('real_volume', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
