# Generated by Django 4.2.1 on 2023-05-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eurusd_d1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eurusd_h1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eurusd_h4',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eurusd_m1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eurusd_m15',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eurusd_m30',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eurusd_m5',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eurusd_w1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gbpusd_d1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gbpusd_h1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gbpusd_h4',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gbpusd_m1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gbpusd_m15',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gbpusd_m30',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gbpusd_m5',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gbpusd_w1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdcad_d1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdcad_h1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdcad_h4',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdcad_m1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdcad_m15',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdcad_m30',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdcad_m5',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdcad_w1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdjpy_d1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdjpy_h1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdjpy_h4',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdjpy_m1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdjpy_m15',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdjpy_m30',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdjpy_m5',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usdjpy_w1',
            name='id',
        ),
        migrations.AlterField(
            model_name='eurusd_d1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='eurusd_h1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='eurusd_h4',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='eurusd_m1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='eurusd_m15',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='eurusd_m30',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='eurusd_m5',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='eurusd_w1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='gbpusd_d1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='gbpusd_h1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='gbpusd_h4',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='gbpusd_m1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='gbpusd_m15',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='gbpusd_m30',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='gbpusd_m5',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='gbpusd_w1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdcad_d1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdcad_h1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdcad_h4',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdcad_m1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdcad_m15',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdcad_m30',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdcad_m5',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdcad_w1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdjpy_d1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdjpy_h1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdjpy_h4',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdjpy_m1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdjpy_m15',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdjpy_m30',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdjpy_m5',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
        migrations.AlterField(
            model_name='usdjpy_w1',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата фрейма'),
        ),
    ]
